#!/usr/bin/env bash

block() {
    local site=$1

    if grep -q "$site" /etc/hosts; then
        echo "$site is already blocked!"
        return 1
    else
        echo -e "127.0.0.1\t$site" | tee -a /etc/hosts > /dev/null
    fi
}

unblock() {
    local site=$1

    if grep -q "$site" /etc/hosts; then
        sed -i'.bak' $'/127.0.0.1\t'"$site"'/d' /etc/hosts
    else
        echo "$site is not blocked!"
        return 1
    fi
}

list() {
    grep 127.0.0.1 /etc/hosts | grep -v localhost | sed $'s/127.0.0.1\t//g'
}

to_seconds() {
    local time_amount=$1
    local time_unit=$2

    local time_multiplier=0
    case $time_unit in
        second|seconds)
            time_multiplier=1
            ;;
        minute|minutes)
            time_multiplier=60
            ;;
        hour|hours)
            time_multiplier=3600
            ;;
        day|days)
            time_multiplier=86400
            ;;
    esac

    local seconds=$((time_amount*time_multiplier))
    echo $seconds
}

action=$1
shift

case $action in
    list)
        list
        ;;
    block|unblock)
        sites=()
        mode='simple'

        while test ${#} -gt 0; do # Loops through all arguments with shift.
            case $1 in
                for)
                    shift
                    time_amount=$1
                    shift
                    time_unit=$1
                    mode='for'
                    ;;
                until)
                    shift
                    until=$1
                    mode='until'
                    ;;
                *)
                    sites+=($1)
                    ;;
            esac
            shift
        done

        while read -r pipe; do
            sites+=($pipe)
        done

        blocked_sites=''

        for site in "${sites[@]}"; do
            eval "${action}" "$site"
            if [[ $? == 0 ]]; then
                case $action in
                    'block')
                        action_msg='Blocked'
                        ;;
                    'unblock')
                        action_msg='Unblocked'
                        ;;
                esac

                case $mode in
                    'simple')
                        echo "$action_msg $site"
                        ;;
                    'for')
                        echo "$action_msg $site for $time_amount $time_unit"
                        ;;
                    'until')
                        echo "$action_msg $site until $until"
                        ;;
                esac

                blocked_sites="$blocked_sites $site"
            fi
        done

        case $action in
            'block')
                reverse_fn='unblock'
                ;;
            'unblock')
                reverse_fn='block'
                ;;
        esac

        case $mode in
            'for')
                seconds=$(to_seconds "$time_amount" "$time_unit")
                (sleep "$seconds"; blk $reverse_fn "$blocked_sites" >& /dev/null)&
                ;;
            'until')
                echo "blk $reverse_fn $blocked_sites" | at "$until"
                ;;
        esac
        ;;
esac
