#!/usr/bin/env bash

to_seconds() {
    local TIME_AMOUNT=$1
    local TIME_UNIT=$2

    local TIME_MULTIPLIER=0
    case $TIME_UNIT in
        second|seconds)
            TIME_MULTIPLIER=1
            ;;
        minute|minutes)
            TIME_MULTIPLIER=60
            ;;
        hour|hours)
            TIME_MULTIPLIER=3600
            ;;
        day|days)
            TIME_MULTIPLIER=86400
            ;;
    esac

    local SECONDS=$(($TIME_AMOUNT*$TIME_MULTIPLIER))
    echo $SECONDS
}

block() {
    local SITE=$1

    if grep -q $SITE /etc/hosts; then
        echo "$SITE is already blocked!"
        return 1
    else
        echo -e "127.0.0.1\t$SITE" | tee -a /etc/hosts > /dev/null
    fi
}

unblock() {
    local SITE=$1

    if grep -q $SITE /etc/hosts; then
        sed -i'.bak' $'/127.0.0.1\t'"$SITE"'/d' /etc/hosts
    else
        echo "$SITE is not blocked!"
        return 1
    fi
}

block_simple() {
    local SITES=$1

    for SITE in ${SITES[@]}; do
        block $SITE

        if [[ $? == 0 ]]; then
            echo "Blocked $SITE"
        fi
    done
}

unblock_simple() {
    local SITES=$1

    for SITE in ${SITES[@]}; do
        unblock $SITE

        if [[ $? == 0 ]]; then
            echo "Unblocked $SITE"
        fi
    done
}

block_for() {
    local SITES=$1
    local TIME_AMOUNT=$2
    local TIME_UNIT=$3

    local SECONDS=$(to_seconds $TIME_AMOUNT $TIME_UNIT)

    for SITE in ${SITES[@]}; do
        block $SITE

        if [[ $? == 0 ]]; then
            (sleep $SECONDS; unblock $SITE >& /dev/null)&
            echo "Blocked $SITE for $TIME_AMOUNT $TIME_UNIT"
        fi
    done
}

unblock_for() {
    local SITES=$1
    local TIME_AMOUNT=$2
    local TIME_UNIT=$3

    local SECONDS=$(to_seconds $TIME_AMOUNT $TIME_UNIT)

    for SITE in ${SITES[@]}; do
        unblock $SITE

        if [[ $? == 0 ]]; then
            (sleep $SECONDS; block $SITE >& /dev/null)&
            echo "Unblocked $SITE for $TIME_AMOUNT $TIME_UNIT"
        fi
    done
}

block_until() {
    local SITES=$1
    local UNTIL=$2

    for SITE in ${SITES[@]}; do
        block $SITE

        if [[ $? == 0 ]]; then
            echo "./block unblock $SITE" | at $UNTIL
            echo "Blocked $SITE until $UNTIL"
        fi
    done
}

unblock_until() {
    local SITES=$1
    local UNTIL=$2

    for SITE in ${SITES[@]}; do
        unblock $SITE

        if [[ $? == 0 ]]; then
            echo "./block block $SITE" | at $UNTIL
            echo "Unblocked $SITE until $UNTIL"
        fi
    done
}

list() {
    cat /etc/hosts | grep 127.0.0.1 | grep -v localhost | sed 's/127.0.0.1\t//g'
}

ACTION=$1
shift

case $ACTION in
    list)
        list
        ;;
    block|unblock)
        SITES=()

        while test ${#} -gt 0 # Loops through all arguments with shift.
        do
            case $1 in
                for)
                    shift
                    TIME_AMOUNT=$1
                    shift
                    TIME_UNIT=$1
                    FN=${ACTION}'_for' # block_for or unblock_for
                    eval ${FN} $SITES $TIME_AMOUNT $TIME_UNIT
                    exit
                    ;;
                until)
                    shift
                    UNTIL=$1
                    FN=${ACTION}'_until' # block_until or unblock_until
                    eval ${FN} $SITES $UNTIL
                    exit
                    ;;
                *)
                    SITES+=($1)
                    ;;
            esac
            shift
        done

        FN=${ACTION}'_simple' # block_simple or unblock_simple
        eval ${FN} $SITES
        ;;
esac
