#!/usr/bin/env bash

block() {
    if grep -q $1 /etc/hosts; then
        echo "$1 is already blocked!"
    else
        echo -e "127.0.0.1\t$1" | sudo tee -a /etc/hosts > /dev/null

        if [[ $2 = 0 ]]; then
            echo "Blocked $1"
        else
            (sleep $2; unblock $1 0 >& /dev/null)&
            echo "Blocked $1 for $2 seconds"
        fi
    fi
}

unblock() {
    if grep -q $1 /etc/hosts; then
        sudo sed -i'.bak' "/127.0.0.1\t$1/d" /etc/hosts

        if [[ $2 = 0 ]]; then
            echo "Unblocked $1"
        else
            (sleep $2; block $1 0 >& /dev/null)&
            echo "Unblocked $1 for $2 seconds"
        fi
    else
        echo "$1 is not blocked!"
    fi
}

list() {
    cat /etc/hosts | grep 127.0.0.1 | grep -v localhost | sed 's/127.0.0.1\t//g'
}

SITE=""
ACTION="add"
TIME=0

while getopts s:rt:l opt; do
    case $opt in
        s)
            SITE=$OPTARG
            ;;
        r)
            ACTION="remove"
            ;;
        t)
            TIME=$OPTARG
            ;;
        l)
            ACTION="list"
            ;;
    esac
done

if [[ $ACTION = "list" ]]; then
    list
    exit
fi

if [[ $SITE ]]; then
    case $ACTION in
        add)
            block $SITE $TIME
            ;;
        remove)
            unblock $SITE $TIME
            ;;
    esac
else
    while read pipe; do
        case $ACTION in
            add)
                block $pipe $TIME
                ;;
            remove)
                unblock $pipe $TIME
                ;;
        esac
    done
fi
